### ISSUE TITLE
WorldGuard v7 NoClassDefFoundError

### ISSUE THREAD

**Issue by TAfirehawk** [GriefPrevention/GriefPrevention#329]
### What behaviour is observed:
Console error when placing chest
### What behaviour is expected:
Looked fine ingame
### Steps/models to reproduce:
Happens every time placing a chest

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot 1705 build with GP 16.8 on fresh 1.13 world

### Stack trace/error

```
[09:59:58 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:153) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.ItemStack.placeItem(ItemStack.java:204) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:504) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/permission/RegionPermissionModel
        at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:36) ~[?:?]
        at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:863) ~[?:?]
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:285) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-69774b3-4d0e2b7]
        ... 18 more
```

### GriefPrevention config.yml (if applicable)

default, no changes

### Plugin list (if applicable):
![image](https://user-images.githubusercontent.com/40474729/43367272-659bb950-9318-11e8-93ba-1722ce46a5f0.png)

**Comment by RoboMWM** [comment]
Mitigate via disabling worldguard integration in config.

Set `CreationRequiresWorldGuardBuildPermission` to `false`

**Comment by RoboMWM** [comment]
Should be fixed in https://github.com/TechFortress/GriefPrevention/releases/tag/16.9.alpha, close this issue if that's the case.

**Comment by NullCase** [comment]
I did not experience this bug while running EssentialsX, WG v7 and GP. 

There is a newer version: EssentialsX-2.15.0.18.jar
